enum ActionTypes{
    SET_INGREDIENTS,
    ADD_INGREDIENT,
    REMOVE_INGREDIENT,
    SET_FETCHING_INGREDIENTS,
    AUTH_START,
    AUTH_SUCCESSFUL,
    AUTH_FAILED,
    AUTH_LOGOUT,
    FETCH_ORDERS_START,
    FETCH_ORDERS_SUCCESS,
    FETCH_ORDERS_FAIL,
    PURCHASE_INIT,
    PURCHASE_START,
    PURCHASE_SUCCESS,
    PURCHASE_FAIL,
    SET_REDIRECT_PATH,
}


export default ActionTypes;